services:
    SilasJoisten\Sonata\MultiUploadBundle\Pool\ProviderChain: ~

    SilasJoisten\Sonata\MultiUploadBundle\Twig\MultiUploadExtension:
        arguments: [ '@SilasJoisten\Sonata\MultiUploadBundle\Pool\ProviderChain' ]
        tags: [ 'twig.extension' ]

